[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx prisma db push && node dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "api"
